name = "Galen"
uuid = "58ff900b-3071-5ad5-aefd-6f26c7ca40c3"
repo = "https://github.com/galenlynch/GalenRegistry.git"
description = "Packages that Galen developed that are not yet public"

[packages]
09a0ae9b-ba3b-5e1c-94b6-f03ec874e73a = { name = "GLFileCache", path = "G/GLFileCache" }
0c649a72-a9cb-5d46-9b0c-e014f97c08cd = { name = "MountainLab", path = "M/MountainLab" }
1751c77c-d90c-5130-9faa-3b4ea8d90a70 = { name = "EventIntervals", path = "E/EventIntervals" }
1899e1d9-0e62-5b08-93e8-96938e3582a6 = { name = "DynamicTimeseries", path = "D/DynamicTimeseries" }
18f53e89-494d-4131-905c-653e8ada6cd8 = { name = "SignalIndices", path = "S/SignalIndices" }
1edc36e0-e0d6-4a03-9cc5-f51062c1a987 = { name = "MscpPaper", path = "M/MscpPaper" }
1f2ffea9-73bd-5d04-b319-71eab08f4cf7 = { name = "NeuroPlots", path = "N/NeuroPlots" }
22e6403b-b5c1-5b07-bdd0-e10e94a3d1a8 = { name = "Chronux", path = "C/Chronux" }
250fb856-b7da-50e3-a87b-ac946a549c37 = { name = "GCaMPAnalysis", path = "G/GCaMPAnalysis" }
34c7ed6b-ff08-5868-b4e9-6a77a2b436e9 = { name = "JoinedArrays", path = "J/JoinedArrays" }
3671797b-b403-50f8-ae8f-9a67aa3877b6 = { name = "PyQtGraph", path = "P/PyQtGraph" }
37bac92b-e4c2-480a-b015-8005f9486f30 = { name = "FeatherScopePrePro", path = "F/FeatherScopePrePro" }
3b513129-edc2-41ad-aa38-53fba2c59579 = { name = "ImageOverlays", path = "I/ImageOverlays" }
429a002d-bc4d-4683-9383-b719270f290d = { name = "SimpleImageRegistration", path = "S/SimpleImageRegistration" }
47645f41-d5a4-5a97-9416-ecfa2f0b970d = { name = "WaveClus", path = "W/WaveClus" }
4e159947-943e-46d2-a8e1-9440738fdb20 = { name = "FeatherScopePlots", path = "F/FeatherScopePlots" }
4f3ae7f7-1a63-5845-9346-bdb28363aa1a = { name = "ShowTree", path = "S/ShowTree" }
54b80fc8-3c35-4556-8cc1-32f813c15580 = { name = "PreciseTimestamps", path = "P/PreciseTimestamps" }
5d3dd9f5-cffe-4d9b-8768-e5b1153cff1e = { name = "CaProcessing", path = "C/CaProcessing" }
65444e21-13b1-5fbd-b269-b51e5fd998ef = { name = "TSConditioning", path = "T/TSConditioning" }
66348666-c7df-5349-9f57-1aa7b70c968c = { name = "EphysScorer", path = "E/EphysScorer" }
792fb28f-c6b2-5f06-a8ac-ad608d2e04a9 = { name = "OEPlotting", path = "O/OEPlotting" }
7df9be73-7dfd-50c0-8315-92cf85547cfe = { name = "RegistryUtils", path = "R/RegistryUtils" }
7f5789ec-5f73-57b2-a383-f6907311fb4c = { name = "InscopixFiles", path = "I/InscopixFiles" }
85caa3df-cadf-5975-918b-2e8fc037b3f4 = { name = "AcqGuiTools", path = "A/AcqGuiTools" }
8b4c6747-1f02-570a-a961-a96037df41d6 = { name = "GLUtilities", path = "G/GLUtilities" }
8f482346-92be-5b4f-b3d2-8fb8a911da8e = { name = "SpykingCircus", path = "S/SpykingCircus" }
98771ce5-7d96-5bd1-bf3e-1fdeced7aaac = { name = "GLBootStrap", path = "G/GLBootStrap" }
aa617110-c04f-5099-8839-5e9d8aa4b2aa = { name = "GLEphys", path = "G/GLEphys" }
ac41db86-e0e2-5699-a8f0-74eb2b42daa9 = { name = "DbCache", path = "D/DbCache" }
acfd8622-5368-561c-8721-366ff6cfe777 = { name = "SpikeAnalysis", path = "S/SpikeAnalysis" }
ae4a1b0c-2eba-53ea-bfa1-4b204b1b4ec7 = { name = "Pillow", path = "P/Pillow" }
b6c59e15-8662-4f8a-b157-cd910e143dcd = { name = "SortedIntervals", path = "S/SortedIntervals" }
ba9f8c08-7079-5968-bb88-5786d7f7fda6 = { name = "RecordingReports", path = "R/RecordingReports" }
bad8ac6d-631b-4a14-ac37-1023b5d57086 = { name = "Lynch2016Data", path = "L/Lynch2016Data" }
c1fc0891-a329-5e3b-bec7-f99dacaec59e = { name = "Munging", path = "M/Munging" }
c8e9901b-98b1-4201-9989-7d8ea213d738 = { name = "CnmfeReports", path = "C/CnmfeReports" }
cb999fff-dc27-5add-ba90-100744871a8d = { name = "GlDbPlotting", path = "G/GlDbPlotting" }
cd509344-b550-11e9-0787-e78261257376 = { name = "FeatherScope", path = "F/FeatherScope" }
cda7f33f-16bd-5acf-8846-697be4d4b9a9 = { name = "OEDiscovery", path = "O/OEDiscovery" }
d375881c-1a96-5303-9718-cbc9093d14c3 = { name = "Phy", path = "P/Phy" }
d859e211-4831-58a2-94f1-1b0ad2592100 = { name = "FeeSqlScripts", path = "F/FeeSqlScripts" }
d95518f9-d624-5c5b-9e70-e2fa41af329d = { name = "OEUtilities", path = "O/OEUtilities" }
dc26a3db-f226-49e4-b913-a88a22652240 = { name = "FeatherscopeExtraction", path = "F/FeatherscopeExtraction" }
dc70017b-e5a2-4350-b176-dd98c31a380c = { name = "CnmfePlots", path = "C/CnmfePlots" }
e0ad81a8-a468-4370-9e62-da670134ef1b = { name = "CnmfeResults", path = "C/CnmfeResults" }
e8059576-bc99-5d04-89a5-9dd3a07e8d35 = { name = "FeeSqlLoader", path = "F/FeeSqlLoader" }
